### PR TITLE
Add list slicing tutorial

### PR DESCRIPTION
**Pull request by mephph**
Quite a few students didn't know how to get only the first part of a list, or reverse a list.

### CODE REVIEW

**Comment by fherwig** [comment]
please see thread in course space Instructor chat

TA examples must start with a pointer to where this material has been covered in class

 the material has been covered in notebook No 5, Part.I under the header 2D arrays.

**Comment by fherwig** [comment]
Could you just add a link to where this was covered in the course notes at the beginning? then it would be nice to have this TA lab added to the repo

thanks, F

**Comment by mephph** [comment]
I'll make the changes later tonight when I'm done work.

**Comment by mephph** [comment]
A bit later than intended, but here you go.

**Pull request merged**
